package com.pgis.caseinfo;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema(description = "案件信息")
public class CaseRecord {
    @Schema(description = "应用ID")
    private String sjhjAppid;
    @Schema(description = "上报批次ID")
    private String sjhjSbpcid;
    @Schema(description = "上报时间")
    private String sjhjSbsj;
    @Schema(description = "加密模式")
    private String sjhjJmms;
    @Schema(description = "下发值")
    private String sjhjXfz;
    @Schema(description = "数据消费时间，毫秒时间戳")
    private String sjxfsj;
    @Schema(description = "部级案件编码")
    private String bjajbm;
    @Schema(description = "案事件编号")
    private String asjbh;
    @Schema(description = "案件名称")
    private String ajmc;
    @Schema(description = "案件来源代码")
    private String ajlydm;
    @Schema(description = "案件来源名称")
    private String ajlymc;
    @Schema(description = "接警单编号")
    private String jjdbh;
    @Schema(description = "移送案件单位名称")
    private String ysajdwmc;
    @Schema(description = "移送案件单位类型代码")
    private String ysajdwlxdm;
    @Schema(description = "移送案件单位类型名称")
    private String ysajdwlxmc;
    @Schema(description = "简要案情")
    private String jyaq;
    @Schema(description = "发现案事件时间")
    private String fxasjsj;
    @Schema(description = "案件发生开始时间")
    private String ajfskssj;
    @Schema(description = "案件发生结束时间")
    private String ajfsjssj;
    @Schema(description = "作案形式代码")
    private String zaxsdm;
    @Schema(description = "作案形式名称")
    private String zaxsmc;
    @Schema(description = "作案时机代码")
    private String zasjdm;
    @Schema(description = "作案时机名称")
    private String zasjmc;
    @Schema(description = "作案时机类别补充描述")
    private String zasjlbbcms;
    @Schema(description = "案件发生地址地域类别代码")
    private String ajfsdzdylbdm;
    @Schema(description = "案件发生地址地域类别名称")
    private String ajfsdzdylbmc;
    @Schema(description = "案件发生地行政区划代码")
    private String ajfsdxzqhdm;
    @Schema(description = "案件发生地行政区划名称")
    private String ajfsdxzqhmc;
    @Schema(description = "案件发生地址经度")
    private String ajfsdzjd;
    @Schema(description = "案件发生地址维度")
    private String ajfsdzwd;
    @Schema(description = "案件发生地址名称")
    private String ajfsdzmc;
    @Schema(description = "涉案场所类别代码")
    private String sacslbdm;
    @Schema(description = "涉案场所类别名称")
    private String sacslbmc;
    @Schema(description = "涉案场所类别补充描述")
    private String sacslbbcms;
    @Schema(description = "案件发生地空间部位类别代码")
    private String ajfsdkjbwlbdm;
    @Schema(description = "案件发生地空间部位类别名称")
    private String ajfsdkjbwlbmc;
    @Schema(description = "案件发生地空间部位补充描述")
    private String ajfsdkjbwbcms;
    @Schema(description = "案件发生地发生楼层")
    private String ajfsdfslc;
    @Schema(description = "案件发生地建筑物层数")
    private String ajfsdjzwcs;
    @Schema(description = "案件发生地是否建筑物内")
    private String ajfsdsfjzwn;
    @Schema(description = "案件发生地是否租赁住宅")
    private String ajfsdsfzlzz;
    @Schema(description = "危害程度")
    private String whcd;
    @Schema(description = "作案人数")
    private String zars;
    @Schema(description = "受伤人数")
    private String ssrs;
    @Schema(description = "死亡人数")
    private String swrs;
    @Schema(description = "损失财物简要情况")
    private String sscwjyqk;
    @Schema(description = "损失价值")
    private String ssjz;
    @Schema(description = "涉案总值")
    private String sazz;
    @Schema(description = "收缴财物价值")
    private String sjcwjz;
    @Schema(description = "作案特征集合描述")
    private String zatjzhms;
    @Schema(description = "现勘编号")
    private String xkbh;
    @Schema(description = "共同犯罪性质代码")
    private String gtfzxzdm;
    @Schema(description = "共同犯罪性质名称")
    private String gtfzxzmc;
    @Schema(description = "涉外因素代码")
    private String swysdm;
    @Schema(description = "涉外因素名称")
    private String swysmc;
    @Schema(description = "涉及国别或地区代码")
    private String sjgbhdqdm;
    @Schema(description = "涉及国别或地区名称")
    private String sjgbhdqmc;
    @Schema(description = "涉外案件涉外情况")
    private String swajswqk;
    @Schema(description = "受理时间")
    private String slsj;
    @Schema(description = "受理单位代码")
    private String sldwdm;
    @Schema(description = "受理单位名称")
    private String sldwmc;
    @Schema(description = "立案日期，YYYYMMDD")
    private String larq;
    @Schema(description = "办案单位代码")
    private String badwdm;
    @Schema(description = "办案单位名称")
    private String badwmc;
    @Schema(description = "主办人身份证号")
    private String zbrsfzh;
    @Schema(description = "主办人联系电话")
    private String zbrlxdh;
    @Schema(description = "主办人姓名")
    private String zbrxm;
    @Schema(description = "督办级别代码")
    private String dbjbdm;
    @Schema(description = "督办级别名称")
    private String dbjbmc;
    @Schema(description = "侦查终结侦查行为依据描述")
    private String zczjzcxwyjms;
    @Schema(description = "侦查终结时间")
    private String zczjsj;
    @Schema(description = "侦查终结单位代码")
    private String zczjdwdm;
    @Schema(description = "侦查终结单位名称")
    private String zczjdwmc;
    @Schema(description = "破案方式代码")
    private String pafsdm;
    @Schema(description = "破案方式名称")
    private String pafsmc;
    @Schema(description = "移送起诉案件审查返回决定代码")
    private String ysqsajscfjdmd;
    @Schema(description = "移送起诉案件审查返回决定名称")
    private String ysqsajscfjdmmc;
    @Schema(description = "转行政案件时间")
    private String zxzajsj;
    @Schema(description = "转行政案件接收单位代码")
    private String zxzajjsdwdm;
    @Schema(description = "转行政案件接收单位名称")
    private String zxzajjsdwmc;
    @Schema(description = "数据操作类型代码")
    private String sjczlxdm;
    @Schema(description = "数据来源")
    private String sjly;
    @Schema(description = "录入时间")
    private String lrsj;
    @Schema(description = "录入单位代码")
    private String lrdwdm;
    @Schema(description = "录入单位名称")
    private String lrdwmc;
    @Schema(description = "录入人姓名")
    private String lrrxm;
    @Schema(description = "录入人身份证号")
    private String lrrsfzh;
    @Schema(description = "修改时间")
    private String xgsj;
    @Schema(description = "修改单位代码")
    private String xgdwdm;
    @Schema(description = "修改单位名称")
    private String xgdwmc;
    @Schema(description = "修改人姓名")
    private String xgrxm;
    @Schema(description = "修改人身份证号")
    private String xgrsfzh;
    @Schema(description = "信息主键编号，雪花ID")
    private String xxzjbh;
    @Schema(description = "问题数据编号")
    private String wtsjbh;
    @Schema(description = "分区日期，YYYYMMDD")
    private String pt;
}
