package com.pgis.alarm;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema(description = "接处警接警单")
public class AlarmRecord {
    @Schema(description = "接警编号，主键")
    private String jjbh;
    @Schema(description = "行政区划代码")
    private String xzqhdm;
    @Schema(description = "行政区划名称")
    private String xzqhmc;
    @Schema(description = "接警单位代码")
    private String jjdwdm;
    @Schema(description = "接警单位名称")
    private String jjdwmc;
    @Schema(description = "关联主接警单编号")
    private String glzjjdbh;
    @Schema(description = "接警类型")
    private String jjlx;
    @Schema(description = "警情来源方式")
    private String jqlyfs;
    @Schema(description = "来话类型")
    private String lhlx;
    @Schema(description = "接警录音号")
    private String jjlyh;
    @Schema(description = "接警员编号")
    private String jjybh;
    @Schema(description = "接警员姓名")
    private String jjyxm;
    @Schema(description = "报警时间，YYYYMMDDHHMMSS")
    private String bjsj;
    @Schema(description = "接警时间，YYYYMMDDHHMMSS")
    private String jjsj;
    @Schema(description = "接警完成时间，YYYYMMDDHHMMSS")
    private String jjwcsj;
    @Schema(description = "报警电话")
    private String bjdh;
    @Schema(description = "报警电话用户名")
    private String bjdhyhm;
    @Schema(description = "报警电话用户地址")
    private String bjdhyhdz;
    @Schema(description = "报警人名称")
    private String bjrxm;
    @Schema(description = "报警人性别代码")
    private String bjrxbdm;
    @Schema(description = "联系电话")
    private String lxdh;
    @Schema(description = "报警人证件代码")
    private String bjrzjdm;
    @Schema(description = "报警人证件号码")
    private String bjrzjhm;
    @Schema(description = "报警地址")
    private String bjdz;
    @Schema(description = "警情地址")
    private String jqdz;
    @Schema(description = "报警内容")
    private String bjnr;
    @Schema(description = "接处警系统建设单位代码")
    private String jcjxtjsdwdm;
    @Schema(description = "接处警系统建设单位名称")
    private String jcjxtjsdwmc;
    @Schema(description = "管辖单位代码")
    private String gxdwdm;
    @Schema(description = "管辖单位名称")
    private String gxdwmc;
    @Schema(description = "警情类别代码")
    private String jqlbdm;
    @Schema(description = "警情类型代码")
    private String jqlxdm;
    @Schema(description = "警情细类代码")
    private String jqxldm;
    @Schema(description = "警情子类代码")
    private String jqzldm;
    @Schema(description = "社会联动单位代码")
    private String shlddwdm;
    @Schema(description = "特征点编号")
    private String tzdbh;
    @Schema(description = "作案人数")
    private String zars;
    @Schema(description = "有无持武器")
    private String ywcwq;
    @Schema(description = "有无危险物质")
    private String ywwxwz;
    @Schema(description = "有无爆炸/泄漏")
    private String ywbzxl;
    @Schema(description = "被困人员情况说明")
    private String bkryqksm;
    @Schema(description = "受伤人员情况说明")
    private String ssryqksm;
    @Schema(description = "死亡人员情况说明")
    private String swryqksm;
    @Schema(description = "是否是外语报警")
    private String sfswybj;
    @Schema(description = "报警人定位X坐标")
    private String bjrdwxzb;
    @Schema(description = "报警人定位Y坐标")
    private String bjrdwyzb;
    @Schema(description = "反向定位X坐标")
    private String fxdwxzb;
    @Schema(description = "反向定位Y坐标")
    private String fxdwyzb;
    @Schema(description = "补充接警内容")
    private String bcjjnr;
    @Schema(description = "警情等级代码")
    private String jqdjdm;
    @Schema(description = "警情处理状态代码")
    private String jqclztdm;
    @Schema(description = "应急救援等级代码")
    private String yjjydjdm;
    @Schema(description = "涉及车号牌种类代码")
    private String sjchpzldm;
    @Schema(description = "涉及车牌号")
    private String sjcph;
    @Schema(description = "是否是危化车辆")
    private String sfswhcl;
    @Schema(description = "入库时间，YYYYMMDDHHMMSS")
    private String rksj;
    @Schema(description = "更新时间")
    private String gxsj;
    @Schema(description = "警情标签")
    private String jqbq;
    @Schema(description = "是否保密")
    private String sfbm;
    @Schema(description = "部级接警单编码")
    private String bjjjdbm;
    @Schema(description = "部级关联主接警单编码")
    private String bjglzjjdbm;
    @Schema(description = "默认时间戳")
    private String mrsjc;
    @Schema(description = "分区日期，YYYYMMDD")
    private String pt;
}
